# Generated by Django 4.1.5 on 2023-01-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_alter_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
